version: '3.8'

services:
  api:
    build: .
    container_name: api_todos
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: todosdb

volumes:
  mongo_data:

networks:
  todoapinet: